### ISSUE TITLE
During Non-Interactive Session Windows Credentials launches the gui input when credential is found.

### ISSUE THREAD

**Issue by blockbomb** [nano-byte/common#103]
Hello All,

I am a user of zero-install and have been attempting to use the tool as a way to describe build environments for my ci/cd build environments.   When proving out my attempts I ran into strange behavior when attempting to resolve internal feeds.  My jenkins agent would hang forever attempting to download a feed hosted on an internal server w/ authentication.

After digging about I found myself at this repository.  It turns out I think I've found the issue.  On top of that I've found a similar way to simulate the issue via a simple command.

assume we are on windows with a cmd.exe instance
assume we have a server: https://test.domain.tld/ 
assume we have a generic credential in the credential storage: 
`cmdkey /generic:https://test.domain.tld/ /user:user /pass:password`

Then issuing the following command would result in the feed being downloaded and executed as usual.

`0install.exe run --refresh https://test.domain.tld/feed.xml`

to expose the problematic behavior
`0install.exe run --refresh https://test.domain.tld/feed.xml 2>NUL`

this will incorrectly prompt the user to input the credentials via gui.  I believe this is due to passing in WindowsCredentialsFlags.None to WindowsCredentials.PromptGui method on the following line.

https://github.com/nano-byte/common/blob/75d0d994248f0858d0d86921cf4b343c59058cb2/src/Common/Net/WindowsNonInteractiveCredentialProvider.cs#L26

this coupled with this excerpt from the windows credentials API 

> The flags CREDUI_FLAG_USERNAME_TARGET_CREDENTIALS and CREDUI_FLAGS_GENERIC_CREDENTIALS are mutually exclusive. If neither is specified, the credential is a domain credential.
-- https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-creduipromptforcredentialsa

I submit that since we don't propagate the flags passed into the WindowsNonInteractiveCredentialProvider but instead set it to the WindowsCredentialsFlags.None we it cannot find my GENERIC and immediatly return because it is defaulting to a domain credential thus prompting the user for an entry.

Solution:
don't use WindowsCredentialsFlags.None but just pass the flags parameter through like the other providers. 

Thanks,
-BB

**Comment by bastianeicher** [comment]
[Zero Install for Windows 2.23.13](https://github.com/0install/0install-win/releases/tag/2.23.13) contains this fix.
